### ISSUE TITLE
When initializing mwc713 height is initially 0

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#297]
When install a new mwc713 3.1.4 instance and run the info command, height is initially 0. I was testing with the rebased 3.1.1 branch as the node.

**Comment by cgilliard** [comment]
<img width="908" alt="Screen Shot 2020-05-07 at 5 35 58 PM" src="https://user-images.githubusercontent.com/7232183/81358169-9a7d2200-908a-11ea-8f70-39442631f469.png">
<img width="784" alt="Screen Shot 2020-05-07 at 5 36 34 PM" src="https://user-images.githubusercontent.com/7232183/81358173-9d781280-908a-11ea-9c36-336948088866.png">


Upon restart, the height shows correctly.

**Comment by cgilliard** [comment]
Steps to reproduce:
1.) mkdir test
2.) cd test
3.) mwc713 -c mwc713.config
4.) Select '1' to create a new instance.
5.) run the info command: wallet713> info

You will see that the height is 0.

**Comment by bayk** [comment]
I think it should be fixed by now. Also there was sync issue as well.  Will double check.

**Comment by yyangli** [comment]
It is still reproducible. 

![Uploading Screen Shot 2020-10-21 at 2.32.50 PM.png…]()

**Comment by yyangli** [comment]
<img width="1227" alt="Screen Shot 2020-10-21 at 2 32 50 PM" src="https://user-images.githubusercontent.com/10201890/96789744-93cd3780-13aa-11eb-8bbb-8bb30c38ae5e.png">

**Comment by yyangli** [comment]
It can still be reproduced.
