### ISSUE TITLE
Sending with mwcmqs stalls wallet for 2 minutes, if receiver not online

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#400]
Don't start a receiver but try to send some coin to it using mwcmqs. The send will be held up for 2 minutes until it times out. While the send is blocked, go to the transactions screen. That screen is stuck trying to load the transactions. Go back to the send screen. The send screen is now stuck trying to load the account info. Chris says mwcmqs used to be async. Not sure what has changed. Chris says that if it has changed to synchronous, then at the very least the user needs to be able to cancel the transaction.

**Comment by bayk** [comment]
mwc713  executing command 1 by one. If mqs is offilne, send will wait for 2 minutes. So that is expected.

In any case, mqs offline isues was fixed, I think yesterday. Send currently checking if connection is online. Moving to fixed

**Comment by jbyrer** [comment]
this doesn't seem to be fixed.  I still see the same functionality using build 20200706.1

**Comment by bayk** [comment]
@jbyrer .  we can't cover 100% of the cases. Fix is about checking if MQS is available. 
So you should disable network then wait until wallet will discover that. That will take time and we can't make it faster.
Next, when MQS listener is off, send should fail quickly and said that MQS is not online.

That is the only scenario that is covered.

**Comment by jbyrer** [comment]
Ah, ok, confirmed that the behavior is as expected from the comment above.
